module.exports = {
  skipWaiting: true,
  clientsClaim: true,
  globDirectory: "public/",
  globPatterns: ["**/*.{css,js,html}"],
  swDest: "public/sw.js",
  globIgnores: [
    "**/Chart.js/**",
    "**/bootstrap.bundle.js",
    "**/bootstrap.bundle.js.map",
    "**/bootstrap.js",
    "**/bootstrap.js.map",
    "**/bootstrap.min.js",
    "**/bootstrap.min.js.map",
    "**/bootstrap/bootstrap-grid.css",
    "**/bootstrap/bootstrap-grid.css.map",
    "**/bootstrap/bootstrap-grid.min.css",
    "**/bootstrap/bootstrap-reboot.css",
    "**/bootstrap/bootstrap-reboot.css.map",
    "**/bootstrap/bootstrap-reboot.min.css",
    "**/bootstrap/bootstrap-reboot.min.css.map",
    "**/bootstrap/bootstrap.css.map",
    "**/bootstrap/bootstrap.min.css",
    "**/bootstrap/bootstrap.min.css.map",
  ],
};
